
spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configslocal
            - classpath:/configslocal/
            - classpath:/configslocal/{application}
  profiles:
    active: native
#        git:
##          uri: https://github.com/filipve1994/microservices/
#          search-paths:
#            - "ms-config-properties/{application}/{profile}"
